const ACTION_TYPE = {
    LOADING_START:"LOADING_START",
    LOADING_END:"LOADING_END",
    ADD_PRODUCT:"ADD_PRODUCT",
    DELETE_PRODUCT:"DELETE_PRODUCT",
    GET_PRODUCTS:"GET_PRODUCTS"
}

export default ACTION_TYPE